serversList = {
	'Brazil' : 'BR1',
	'Europe Nordic & East' : 'EUN1',
	'Europe West' : 'EUW1',
	'Japan' : 'JP1',
	'Republic of Korea' : 'KR',
	'Latin America North' : 'LA1',
	'Latin America South' : 'LA2',
	'Middle East' : 'ME1',
	'North America' : 'NA1',
	'Oceania' : 'OC1',
	'Russia' : 'RU',
	'Singapore' : 'SG2',
	'Turkey' : 'TR1',
	'Taiwan' : 'TW2',
	'Vietnam' : 'VN2',
}

langOpts = {
        'Czech (Czech Republic)' : 'cs_CZ',
        'Greek (Greece)' : 'el_GR',
        'Polish (Poland)' : 'pl_PL',
        'Romanian (Romania)' : 'ro_RO',
        'Hungarian (Hungary)' : 'hu_HU',
        'English (United Kingdom)' : 'en_GB',
        'German (Germany)' : 'de_DE',
        'Spanish (Spain)' : 'es_ES',
        'Italian (Italy)' : 'it_IT',
        'French (France)' : 'fr_FR',
        'Japanese (Japan)' : 'ja_JP',
        'Korean (Korea)' : 'ko_KR',
        'Spanish (Mexico)' : 'es_MX',
        'Spanish (Argentina)' : 'es_AR',
        'Portuguese (Brazil)' : 'pt_BR',
        'English (United States)' : 'en_US',
        'English (Australia)' : 'en_AU',
        'Russian (Russia)' : 'ru_RU',
        'Turkish (Turkey)' : 'tr_TR',
        'Malay (Malaysia)' : 'ms_MY',
        'English (Republic of the Philippines)' : 'en_PH',
        'English (Singapore)' : 'en_SG',
        'Thai (Thailand)' : 'th_TH',
        'Vietnamese (Viet Nam)' : 'vi_VN',
        'Indonesian (Indonesia)' : 'id_ID',
        'Chinese (Malaysia)' : 'zh_MY',
        'Chinese (China)' : 'zh_CN',
        'Chinese (Taiwan)' : 'zh_TW',
    }